; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Marauder-Mini]
board = esp32dev
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-mini>
build_flags =
	${env.build_flags}
	${env_4mb.build_flags}

	-Iboards/marauder-mini

	-D MARAUDER_MINI
	-DCONFIG_BT_NIMBLE_ENABLED
	-UCONFIG_BT_BLUEDROID_ENABLED
	-DUSER_SETUP_LOADED=1
	-DST7735_DRIVER=1
	-DST7735_GREENTAB3
	-DTFT_RGB_ORDER=TFT_BGR
	-DTFT_WIDTH=128
	-DTFT_HEIGHT=160
	-DTFT_MISO=19
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_BL=32
	-DTFT_CS=17
	-DTFT_DC=16
	-DTFT_RST=5
	-DTFT_BACKLIGHT_ON=HIGH
	-DTFT_BRIGHT_Bits=8
	-DTFT_BRIGHT_FREQ=5000
	-DSMOOTH_FONT=1
    -DUSE_NRF24_VIA_SPI
	-DNRF24_CE_PIN=22
	-DNRF24_SS_PIN=SPI_SS_PIN
	-DNRF24_MOSI_PIN=SPI_MOSI_PIN
	-DNRF24_SCK_PIN=SPI_SCK_PIN
	-DNRF24_MISO_PIN=SPI_MISO_PIN
	-D SPI_FREQUENCY=27000000
	-D SPI_READ_FREQUENCY=16000000
	-D SPI_TOUCH_FREQUENCY=2500000
	-DTOUCH_CS=-1

	-DDEVICE_NAME='"Marauder mini"'

lib_deps =
	${env.lib_deps}

lib_ignore =
	${env_4mb.lib_ignore}

[env:Awok-Mini]
extends = env:Marauder-Mini
board_build.partitions = custom_16Mb.csv
board_upload.maximum_size = 16777216
board_upload.flash_size=16MB

[env:Marauder-v7]
board = esp32dev
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-mini>
build_flags =
	${env.build_flags}
	${env_4mb.build_flags}
	-Iboards/marauder-mini

	-D MARAUDER_MINI
	-DUSER_SETUP_LOADED=1
	-DILI9341_DRIVER=1
	-DUSE_HSPI_PORT=1
	-DTFT_HEIGHT=320
	-DTFT_WIDTH=240
	-DTFT_MISO=19
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_CS=17
	-DTFT_DC=26
	-DTFT_RST=-1
	-DTFT_BL=32
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DTOUCH_CS=-1
	-DSPI_FREQUENCY=27000000
	-DDEVICE_NAME='"Marauder v7"'

lib_deps =
	${env.lib_deps}

lib_ignore =
	${env_4mb.lib_ignore}

[env:LAUNCHER_Marauder-Mini]
extends=env:Marauder-Mini
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:Marauder-Mini.build_flags}
	${env_light.build_flags}
lib_deps =
	${env_light.lib_deps}

[env:LAUNCHER_Marauder-v7]
extends=env:Marauder-v7
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:Marauder-v7.build_flags}
	${env_light.build_flags}
lib_deps =
	${env_light.lib_deps}
